python -m torch.distributed.launch examples/run_xfun_re.py \
        --model_name_or_path microsoft/layoutlmv2-base-uncased \
        --output_dir results_re \
        --do_train \
        --do_eval \
        --max_steps 3000 \
        --warmup_ratio 0.1 \
        --evaluation_strategy "steps" \
        --logging_strategy "steps" \
        --save_strategy "steps" \
        --eval_steps 1000 \
        --save_steps 1000 \
        --logging_steps 1 \
        --per_device_train_batch_size=2 \
        --per_device_eval_batch_size=1 \
        --num_train_epochs 5 \
        --config_name layoutlmv2_config.json \
        --report_to tensorboard \
        --return_entity_level_metrics \
